services:
  backend:
    image: backend:latest
    container_name: backend
    restart: always
    ports:
      - "8000:8000"
    build:
        context: ./backend
    environment:
      HOST: "0.0.0.0"

    develop:
      watch:
        - action: sync
          path: ./backend
          target: /app/backend
  
  frontend:
    image: frontend:latest
    container_name: frontend
    restart: always
    ports:
      - "5173:5173"
    build:
        context: ./frontend

    develop:
      watch:
        - action: sync
          path: ./frontend
          target: /app/frontend
    